### ISSUE TITLE
how to acess the app? not listening at 3000 port.

### ISSUE THREAD

**Issue by bimalkjha** [data-henrik/db2visitors#1]
I cloned db2visitors from github and created db2cred.json file to run the app locally. I am able to run the app as below:

```
$ node app.js
we are local
App started on port 3000
```

After this I tried to access `http://localhost:3000/` in my browser, but unable to get anything. Am I accessing correct url? I am getting error that Firefox can not establish connection to the server.

**Comment by bimalkjha** [comment]
Well, I updated app.listen in app.js as below and it started working.
`app.listen(port, function(){})`

localhost:3000 gives me below result:

```
Hi there!

Thanks for visiting my DB2 on IBM Bluemix application.

This is what I know about you and got stored in DB2:

Your IP address: 9.109.163.52

Your city: Durham

Your country (maybe...): United States/US

And all what is reported: {"ip":"9.109.163.52","country_code":"US","country_name":"United States","region_code":"NC","region_name":"North Carolina","city":"Durham","zip_code":"27709","time_zone":"America/New_York","latitude":35.994,"longitude":-78.899,"metro_code":560}
```

On console, I get below output:

```
yes, called
insertIP called { ip: '9.109.163.52',
  country_code: 'US',
  country_name: 'United States',
  region_code: 'NC',
  region_name: 'North Carolina',
  city: 'Durham',
  zip_code: '27709',
  time_zone: 'America/New_York',
  latitude: 35.994,
  longitude: -78.899,
  metro_code: 560 }
{ [Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004',
  state: 'HY004' }
Connection Closed
```

**Comment by data-henrik** [comment]
I don't have time right now to look into it due to travel. However, changing the parameters of the execute() statement in db2access.js succeeded in inserting a record again. Not sure what has changed, but could be that "massaging" the values of the IP record is needed before passing them as parameters to execute().
